version: "3.8"
services:
  db:
    container_name: web_db_compose
    image: postgres:16.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: web_db
    ports:
      - "5432:5432"

  backend:
    container_name: web_backend
    build:
      context: ./backend 
    depends_on:
      - db
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/web_db?schema=public"
      SECRET_KEY: "iuwejhtjskgnhr10ph1j4375y135yfa345"
      CORS_HOST_URL: "http://localhost:3000"
    command: ["node", "server.js"]

  frontend:
    container_name: web_frontend
    build:
      context: ./frontend 
    ports:
      - "3000:3000"
    environment:
      BACKEND_HOST: "http://localhost:4000"
    command: ["npm", "start"]
