version: "3.8"
services:
  db:
    container_name: web_db_compose
    image: postgres:16.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: web_db
    ports:
      - "5432:5432"

  backend:
    build: .
    depends_on:
      - db
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/game_db?schema=public"
    command: ["node", "server.js"]
